### ISSUE TITLE
position error!

### ISSUE THREAD

**Issue by JackCheng3334** [arcadefire/nice-spinner#119]
Choose either the first or the second item, the "position" returned are both 0.

**Comment by caixiquan** [comment]
Me too！Do you have a good idea to solve this problem？

**Comment by Jawadwithw** [comment]
In setOnItemSelectedListener method, just forget about the position value , get the item index with :
niceSpinner.getSelectedIndex().
that will work :)

**Comment by arcadefire** [comment]
Can you show me the code snippet that reproduces this issue? I've been trying the example app and it works there.

**Comment by arcadefire** [comment]
This was fixed with: da73d7796ae4b937db124a86d4101d6d0f44db70.  Now the position value should return the expected value. 

Note: Due to the nature of the spinner, a method call to `parent.getItemAtPosition` will return a wrong value, though, as the entries displayed by the pop-up list and the ones contained in the adapter are different: the selected item won't be displayed within the list.

To avoid getting the wrong value from the parent, I've deprecated the current listeners' interface and created a brand new one that solves the problem. The sample project app has been updated to show the new approach.

**Comment by arcadefire** [comment]
Closing this. Feel free to open a new issue if the problem persists.

**Comment by asknask** [comment]
@arcadefire Still getting this issue on 1.4.5 using the new `setOnSpinnerItemSelectedListener(parent, view, position, id)`.

Here's a summary of the issue:

My list has 'item 0' (at index 0, dropdown 0), 'item 1 (at index 1, dropdown 1)'.
When the screen loads, dropdown 0 is selected by default. Dropdown 1 has item 1. I select dropdown 1. Works normally.

However, when I click the dropdown again, it now shows item 0 at dropdown 1. The library has basically rearranged the indexes however my original list remains in its normal state. Now when I click the dropdown 1 item, my list returns item 1 instead of item 0.

Does this make sense to you?
